-- Cria e popula case_studies com os Casos de Estudo do OPSI, associados à respetiva
-- dimensão, para a secção "Casos de Estudo do OPSI – Observatório de Inovação do Setor
-- Público" no detalhe de indicador. Substitui os 3 cartões mock fixos.
-- Fonte: "July 2026 - Case Studies.xlsx" (Google Drive, partilhado pela OCDE).
--
-- Um caso de estudo pode estar associado a mais do que uma dimensão (o Excel tinha
-- "Acessibilidade/Imparcialidade e Professionalismo" numa só célula, para 4 casos) —
-- por isso a relação é modelada com uma tabela de junção, não uma FK direta.
--
-- Mapeamentos de nome assumidos (variação de nome/ortografia entre Excel e BD, decisão
-- do responsável do projeto):
--   "Capacidade de Resposta e Eficiência" (Excel) → "Capacidade de Resposta e Desempenho" (BD)
--   "Imparcialidade e Professionalismo" (Excel, com "ss") → "Imparcialidade e Profissionalismo" (BD)
--
-- Nota: o Excel também tinha 20 casos de estudo para "Interoperabilidade", "Segurança da
-- Informação e Dados Abertos" e "Envolvimento dos Utilizadores" — dimensões que não
-- existem na plataforma atual (mesma situação já identificada na migration 017 para as
-- sugestões de inovação). Ficam de fora por agora, pendente de revisão com a OCDE/ARTE
-- — ver docs/open-questions.md.

CREATE TABLE case_studies (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  country TEXT NOT NULL,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  external_url TEXT,
  display_order INTEGER,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE TABLE case_study_thematic_priorities (
  case_study_id UUID NOT NULL REFERENCES case_studies(id) ON DELETE CASCADE,
  thematic_priority_id UUID NOT NULL REFERENCES thematic_priorities(id) ON DELETE CASCADE,
  PRIMARY KEY (case_study_id, thematic_priority_id)
);

ALTER TABLE case_studies ENABLE ROW LEVEL SECURITY;
ALTER TABLE case_study_thematic_priorities ENABLE ROW LEVEL SECURITY;

CREATE POLICY leitura_publica ON case_studies FOR SELECT USING (true);
CREATE POLICY leitura_publica ON case_study_thematic_priorities FOR SELECT USING (true);

WITH raw(country, title, description, external_url, display_order, dimensions) AS (
  VALUES
    ('Grécia', 'Uma Plataforma Digital para Pessoas com Deficiência', 'O Serviço Público de Emprego da Grécia (DYPA) desenvolveu a plataforma digital PROSVASIS, concebida de acordo com as mais recentes diretrizes de acessibilidade digital. A iniciativa permite que pessoas com deficiências visuais, auditivas, físicas e cognitivas acedam aos conteúdos e serviços do organismo de forma mais autónoma, contribuindo para uma maior inclusão e igualdade no acesso aos serviços públicos.', 'https://oecd-opsi.org/innovations/digital-platform-disabilities/', 1, ARRAY['Acessibilidade']),
    ('Noruega', 'Loja de Serviços – Gestão de Serviços Municipais pelos Utilizadores', 'O município de Larvik desenvolveu o Service Shop, uma solução digital de marcação e gestão de serviços municipais. A iniciativa permite que os utilizadores agendem serviços de acordo com a sua disponibilidade, ao mesmo tempo que otimiza o planeamento interno através da geração automática de fluxos de trabalho para os funcionários.', 'https://oecd-opsi.org/innovations/service-shop-user-management-of-municipal-services/', 2, ARRAY['Acessibilidade']),
    ('Peru', 'Superando a Complexidade nos Serviços Públicos: Facilitando o Acesso ao Sistema de Eliminação de Barreiras Burocráticas', 'O INDECOPI redesenhou os formulários de apresentação de queixas com base em conhecimentos da economia comportamental. A iniciativa orienta os utilizadores ao longo do processo, identifica informação em falta e disponibiliza apoio através de códigos QR, contribuindo para reduzir erros e melhorar a eficiência do tratamento dos pedidos.', 'https://oecd-opsi.org/innovations/unlocking-labour-markets-removing-bureaucratic-barriers-to-enhance-opportunities-for-the-young-workforce/', 3, ARRAY['Satisfação e Impacto']),
    ('Brasil', 'Programa Justiça Cidadã', 'O Tribunal de Justiça do Estado de Roraima implementou o Programa Justiça Cidadã para alargar o acesso aos serviços jurídicos em regiões remotas. A iniciativa combina pontos de atendimento permanentes e soluções digitais para apoiar comunidades indígenas, ribeirinhas e migrantes, contribuindo para um acesso mais inclusivo à justiça', 'https://oecd-opsi.org/innovations/programa-justica-cidada-citizen-justice-program/', 4, ARRAY['Acessibilidade','Imparcialidade e Profissionalismo']),
    ('Brasil', 'Excluídos Digitais', 'A Ouvidoria-Geral da União do Brasil desenvolveu uma solução para integrar pedidos recebidos através de diferentes canais, incluindo correspondência em papel, correio eletrónico e plataformas digitais. A iniciativa assegura que cidadãos digitalmente excluídos podem aceder aos serviços públicos através do canal mais adequado às suas necessidades, contribuindo para uma prestação de serviços mais inclusiva.', 'https://oecd-opsi.org/innovations/digital-outcasts/', 5, ARRAY['Acessibilidade','Imparcialidade e Profissionalismo']),
    ('Geórgia', 'Serviços de Emergência e Serviços Essenciais para Pessoas com Deficiência', 'O Governo da Geórgia desenvolveu novos canais de acesso aos serviços de emergência e registo civil para pessoas surdas e com deficiência auditiva. A iniciativa foi concebida em estreita colaboração com os utilizadores e contribui para uma prestação de serviços mais inclusiva e equitativa', 'https://oecd-opsi.org/innovations/emergency-and-primary-services-for-people-with-disabilities/', 6, ARRAY['Acessibilidade','Imparcialidade e Profissionalismo']),
    ('Espanha', 'Adaptar Linguagem para Pessoas com Deficiência', 'O Governo de Aragão desenvolveu o programa Easy Government para adaptar textos legais e administrativos às necessidades de pessoas com dificuldades de compreensão. A iniciativa promove uma comunicação mais inclusiva e acessível, contribuindo para uma prestação de serviços mais equitativa', 'https://oecd-opsi.org/innovations/easy-government/', 7, ARRAY['Acessibilidade','Imparcialidade e Profissionalismo']),
    ('Uruguai', 'Inteligência Artificial para Classificação de Pedidos no Balcão de Atendimento ao Cidadão', 'A Agência de Governo Eletrónico do Uruguai implementou um sistema de inteligência artificial para classificar automaticamente os pedidos recebidos nos serviços de atendimento ao cidadão. A iniciativa utiliza processamento de linguagem natural para categorizar solicitações, contribuindo para reduzir custos operacionais, otimizar recursos e acelerar os tempos de resposta.', 'https://oecd-opsi.org/innovations/ai-service-requests-classification/', 8, ARRAY['Capacidade de Resposta e Desempenho']),
    ('Suécia', 'Novas Formas de Prestação de Apoio Social através da Automatização de Processos', 'O município de Trelleborg automatizou tarefas administrativas rotineiras associadas à gestão das prestações sociais. A iniciativa aumentou a eficiência dos processos e permitiu que os profissionais dedicassem mais tempo ao apoio direto aos cidadãos e às suas necessidades.', 'https://oecd-opsi.org/innovations/9131-2/', 9, ARRAY['Capacidade de Resposta e Desempenho']),
    ('Coreia do Sul', 'SAFE-i24 – Inspeção Automatizada nas Fronteiras', 'O Ministério da Segurança Alimentar e dos Medicamentos da Coreia desenvolveu o sistema SAFE-i24 para automatizar a análise das declarações de importação de alimentos. A iniciativa permite processar pedidos em poucos minutos, 24 horas por dia, contribuindo para reduzir encargos administrativos, acelerar procedimentos e melhorar a experiência dos utilizadores.', 'https://oecd-opsi.org/innovations/safe-i24-automated-inspection-at-the-border/', 10, ARRAY['Capacidade de Resposta e Desempenho']),
    ('Brasil', 'Centro Partilhado de Serviços ColaboraGov', 'O Governo do Brasil desenvolveu o Centro Partilhado de Serviços ColaboraGov para centralizar serviços administrativos prestados a vários ministérios. A iniciativa promove ganhos de eficiência, normalização de processos e partilha de recursos, contribuindo para uma prestação de serviços mais ágil e consistente', 'https://oecd-opsi.org/innovations/shared-services-center-colaboragov-an-innovative-model-for-delivering-administrative-services/', 11, ARRAY['Capacidade de Resposta e Desempenho']),
    ('Irlanda', 'Validação dos Tempos Média de Espera', 'O Departamento da Saúde da Irlanda redesenhou o processo de validação das listas de espera hospitalares utilizando conhecimentos da economia comportamental. A iniciativa melhora a qualidade da informação sobre a procura efetiva dos serviços, contribuindo para uma gestão mais eficiente das listas de espera', 'https://oecd-opsi.org/innovations/using-behavioural-insights-to-increase-patient-engagement-with-validation-of-hospital-waiting-lists/', 12, ARRAY['Capacidade de Resposta e Desempenho']),
    ('Reino Unido', 'Norma de Transparência Algorítmica', 'O Governo do Reino Unido desenvolveu uma norma de transparência algorítmica para divulgar de forma clara a utilização de algoritmos na tomada de decisão pública. A iniciativa promove a transparência, a responsabilização e a confiança dos cidadãos na utilização de dados e tecnologias digitais pela administração pública.', 'https://oecd-opsi.org/innovations/algorithmic-transparency-standard/', 13, ARRAY['Imparcialidade e Profissionalismo']),
    ('Ucrânia', 'Formação de Funcionários Públicos sobre uma Abordagem Baseada nos Direitos Humanos', 'O PNUD na Ucrânia desenvolveu um programa de formação para reforçar a integração dos direitos humanos e da igualdade de género na conceção de políticas e serviços digitais. A iniciativa capacita os funcionários públicos para desenvolver serviços mais inclusivos e centrados nas necessidades dos utilizadores', 'https://oecd-opsi.org/innovations/training-for-public-servants-on-human-rights-based-approach-in-public-policy-design/', 14, ARRAY['Imparcialidade e Profissionalismo']),
    ('Brasil', 'Garantir a Imparcialidade através do Anonimato dos Requerentes em Pedidos de Acesso à Informação', 'A Controladoria-Geral da União do Brasil implementou uma funcionalidade que permite aos utilizadores apresentar pedidos de acesso à informação de forma anónima. A iniciativa reduz o risco de enviesamentos conscientes ou inconscientes por parte dos funcionários públicos, contribuindo para uma maior imparcialidade e equidade no tratamento dos pedidos.', 'https://oecd-opsi.org/innovations/ensuring-impartiality-through-identity-neutrality-provisions-the-case-of-freedom-of-information-in-brazil/', 15, ARRAY['Imparcialidade e Profissionalismo']),
    ('Azerbaijão', 'Atribuição Proativa e Centrada no Cidadão de Benefícios Sociais', 'O Governo do Azerbaijão desenvolveu um sistema baseado em inteligência artificial para identificar automaticamente cidadãos elegíveis para benefícios sociais. A iniciativa permite a atribuição proativa de prestações sem necessidade de candidatura, contribuindo para um acesso mais rápido, simples e equitativo aos serviços sociais.', 'https://oecd-opsi.org/innovations/proactive-people-centred-assignment-of-social-benefits-in-azerbaijan/', 16, ARRAY['Procura']),
    ('Estónia', 'Serviços Baseados em Eventos de Vida', 'O Governo da Estónia desenvolveu uma plataforma de serviços baseada em eventos de vida para simplificar a interação dos cidadãos com a administração pública. A iniciativa reúne informação e serviços relevantes num único ponto de acesso, contribuindo para experiências mais integradas e proativas.', 'https://oecd-opsi.org/innovations/life-event-based-services-in-estonia/', 17, ARRAY['Procura']),
    ('Arábia Saudita', 'Previsão de Faltas a Consultas Externas', 'O Ministério da Saúde da Arábia Saudita desenvolveu um sistema de inteligência artificial para prever quais os utentes com maior probabilidade de faltar a consultas. A iniciativa utiliza dados clínicos e históricos de marcações para apoiar intervenções preventivas, contribuindo para uma utilização mais eficiente dos recursos de saúde', 'https://oecd-opsi.org/innovations/no-show-prediction-at-outpatient-clinic/', 18, ARRAY['Procura']),
    ('Austrália', 'Modelo de Previsão da Procura dos Serviços Futuros dos Bombeiros e Serviços de Emergência de Queensland', 'O Serviço de Bombeiros e Emergência de Queensland desenvolveu um modelo de previsão da procura baseado em ciência de dados e aprendizagem automática. A iniciativa permite antecipar necessidades futuras de serviço e apoiar decisões de planeamento e investimento, contribuindo para uma gestão mais eficaz dos recursos públicos.', 'https://oecd-opsi.org/innovations/queensland-fire-emergency-services-futures-service-demand-forecasting-model/', 19, ARRAY['Procura']),
    ('Finlândia', 'Aurora IA', 'O Governo da Finlândia desenvolveu a plataforma AuroraAI para ligar os cidadãos a serviços relevantes com base nos seus eventos de vida e necessidades de bem-estar. A iniciativa utiliza inteligência artificial para antecipar necessidades futuras e recomendar serviços adequados de forma proativa, contribuindo para uma prestação de serviços mais personalizada, atempada e centrada nas pessoas', 'https://oecd-opsi.org/innovations/auroraai/', 20, ARRAY['Procura']),
    ('Polónia', 'Sistema de Monitorização de Serviços Públicos', 'O Instituto de Estatística da Polónia desenvolveu um Sistema de Monitorização de Serviços Públicos para apoiar a avaliação da quantidade, qualidade, acessibilidade e eficiência dos serviços públicos. A iniciativa disponibiliza indicadores comparáveis e informação de desempenho para apoiar a tomada de decisão e a melhoria contínua dos serviços', 'https://oecd-opsi.org/innovations/public-services-monitoring-system/', 21, ARRAY['Satisfação e Impacto']),
    ('Canadá', 'Utilização de Inquéritos de Experiência do Cliente para Melhorar a Prestação de Serviços', 'O Departamento de Emprego e Desenvolvimento Social do Canadá desenvolveu um modelo de inquérito de experiência do cliente para recolher feedback sistemático dos utilizadores. A iniciativa permite medir satisfação, acessibilidade e eficácia dos serviços, contribuindo para a melhoria contínua da prestação dos serviços públicos.', 'https://oecd-opsi.org/innovations/development-and-implementation-of-a-client-experience-measurement-survey-model-as-part-of-a-specific-client-feedback-strategy/', 22, ARRAY['Satisfação e Impacto']),
    ('Dinamarca', 'Gestão Inovadora de Reclamações', 'O município de Gentofte implementou uma abordagem inovadora à gestão de reclamações, tratando-as como uma fonte de aprendizagem e melhoria. A iniciativa permite identificar oportunidades de inovação e aperfeiçoar os serviços públicos com base nas experiências dos utilizadores.', 'https://oecd-opsi.org/innovations/innovative-complaint-management/', 23, ARRAY['Satisfação e Impacto']),
    ('Brasil', 'Ouvir as Pessoas: Entrevistas Telefónicas Assistidas por Computador para Avaliar Serviços Públicos', 'O Governo do Distrito Federal desenvolveu um modelo de recolha sistemática de opiniões dos cidadãos através de entrevistas telefónicas assistidas por computador. A iniciativa permite avaliar a qualidade dos serviços públicos e produzir evidência fiável para apoiar a tomada de decisão e a melhoria dos serviços.', 'https://oecd-opsi.org/innovations/hearing-the-people-computer-assisted-telephone-interviewing-to-evaluate-public-services/', 24, ARRAY['Satisfação e Impacto']),
    ('Finlândia', 'Ferramentas de Qualidade Suomi.fi', 'A Agência Digital da Finlândia desenvolveu as Ferramentas de Qualidade Suomi.fi para avaliar, monitorizar e comparar a qualidade dos serviços digitais. A iniciativa recolhe feedback dos utilizadores em tempo real e disponibiliza indicadores de utilização e qualidade, contribuindo para a melhoria contínua dos serviços e para uma gestão baseada em evidência.', 'https://oecd-opsi.org/innovations/suomi-fi-quality-tools/', 25, ARRAY['Satisfação e Impacto']),
    ('Colombia', 'Painel de Reclamações dos Cidadãos de Bogotá', 'A cidade de Bogotá desenvolveu um Painel de Controlo de Reclamações dos Cidadãos para monitorizar reclamações, sugestões e elogios relacionados com os serviços públicos. A iniciativa permite identificar preocupações recorrentes, acompanhar tempos de resposta e apoiar a melhoria contínua da qualidade dos serviços', 'https://oecd-opsi.org/innovations/bogotas-citizen-complaints-dashboard/', 26, ARRAY['Satisfação e Impacto']),
    ('Uganda', 'Sistema de Recolha de Feedback - SEMA', 'A SEMA desenvolveu uma plataforma de recolha de feedback em tempo real sobre os serviços públicos, utilizando tecnologias acessíveis a diferentes grupos da população. A iniciativa permite avaliar a qualidade dos serviços e identificar problemas de eficiência, discriminação ou corrupção, contribuindo para uma prestação de serviços mais responsiva e centrada nos cidadãos', 'https://oecd-opsi.org/innovations/sema/', 27, ARRAY['Satisfação e Impacto']),
    ('Estados Unidos da América', 'Comité de Melhoria da Experiência do Utilizador', 'O Departamento de Agricultura dos Estados Unidos desenvolveu o Customer Experience Enhancement Committee para melhorar a experiência dos utilizadores dos seus serviços. A iniciativa reúne funcionários de diferentes organismos para identificar desafios recorrentes e desenvolver soluções centradas nas necessidades dos cidadãos.', 'https://oecd-opsi.org/innovations/fpac-customer-experience-enhancement-committee-cxec/', 28, ARRAY['Satisfação e Impacto']),
    ('Argentina', 'Redesenho do Serviço de Atribuição do Certificado Único de Incapacidade', 'O Governo da Argentina redesenhou o processo de atribuição do Certificado Único de Incapacidade com base numa abordagem centrada no utilizador. A iniciativa reduziu significativamente a complexidade do processo e disponibilizou apoio digital aos requerentes, contribuindo para um acesso mais simples e rápido ao serviço.', 'https://oecd-opsi.org/innovations/certificado-unico-de-discapacidad-cud-redesign-of-the-granting-service-of-the-unique-certificate-of-disability/', 29, ARRAY['Simplicidade']),
    ('Austrália', 'Programa Amigável de Aprovações para Pequenas Empresas', 'A Small Business Development Corporation da Austrália Ocidental implementou o programa Small Business Friendly Approvals para simplificar processos regulamentares. A iniciativa analisou os procedimentos do ponto de vista dos empresários e promoveu reformas destinadas a reduzir encargos administrativos e acelerar aprovações.', 'https://oecd-opsi.org/innovations/small-business-friendly-approvals-program/', 30, ARRAY['Simplicidade']),
    ('Itália', 'Simplificação de Textos para Cidadãos através de Inteligência Artificial Generativa', 'O Instituto Nacional da Segurança Social de Itália implementou uma solução de inteligência artificial generativa para simplificar comunicações dirigidas aos cidadãos. A iniciativa converte documentos complexos em linguagem clara, mantendo a precisão jurídica e melhorando a compreensão da informação pelos utilizadores', 'https://oecd-opsi.org/innovations/text-simplification-for-citizens-with-genai/', 31, ARRAY['Simplicidade']),
    ('Brasil', 'Programa Municipal de Linguagem Simples', 'A Câmara Municipal de São Paulo implementou um programa de linguagem simples para melhorar a comunicação entre a administração pública e os cidadãos. A iniciativa capacita funcionários públicos e promove a simplificação de documentos, contribuindo para uma maior clareza e acessibilidade da informação.', 'https://oecd-opsi.org/innovations/municipal-simple-language-programme/', 32, ARRAY['Simplicidade']),
    ('Brasil', 'Recomendação de Serviços e Perfis de Utilizador com Inteligência Artificial para Melhorar a Experiência dos Cidadãos', 'O Governo do Brasil desenvolveu mecanismos de inteligência artificial na plataforma gov.br para recomendar serviços com base no histórico de navegação dos utilizadores e organizar conteúdos através de perfis de utilizador. A iniciativa permite direcionar os cidadãos para os serviços mais relevantes ao longo das suas jornadas, contribuindo para uma experiência mais personalizada e eficiente.', 'https://oecd-opsi.org/innovations/ai-and-user-profiles/', 33, ARRAY['Simplicidade'])
), inserted AS (
  INSERT INTO case_studies (country, title, description, external_url, display_order)
  SELECT country, title, description, external_url, display_order FROM raw
  RETURNING id, title
)
INSERT INTO case_study_thematic_priorities (case_study_id, thematic_priority_id)
SELECT i.id, tp.id
FROM raw r
JOIN inserted i ON i.title = r.title
JOIN LATERAL unnest(r.dimensions) AS d(name) ON true
JOIN thematic_priorities tp ON tp.name_pt = d.name;
