-- Completa case_studies com os 20 casos de estudo que a migration 018 tinha deixado de
-- fora "por agora, pendente de revisão com a OCDE/ARTE" — porque, nessa altura, as
-- dimensões "Interoperabilidade", "Segurança da Informação e Dados Abertos" e
-- "Envolvimento dos Utilizadores" ainda não existiam na plataforma (só passaram a
-- existir com as migrations 032/033, que renomearam "Integração e Continuidade" →
-- "Interoperabilidade", "Envolvimento das partes interessadas" → "Envolvimento dos
-- Utilizadores", e criaram de novo "Segurança da Informação e Dados Abertos").
-- Ninguém voltou a inserir estes 20 casos depois disso — feedback do cliente
-- (2026-07-16): "Envolvimento dos Utilizadores não apresenta casos; Segurança da
-- Informação também não apresenta casos".
--
-- Fonte: "July 2026 - Case Studies.xlsx" (docs/Casos de estudo/), mesmas 20 linhas
-- identificadas na nota da migration 018. URLs extraídos do hyperlink real de cada
-- célula "Link" (o texto visível é só o título do artigo, não o URL) — mesmo método
-- usado nos 33 casos já inseridos. Corrigido o URL do caso "JAKI" (tinha "ttps://" em
-- vez de "https://" e um espaço à frente na fonte). Descrição do caso "SmartStart"
-- traduzida para PT-PT por consistência com os restantes (a fonte tinha-a em inglês).

WITH raw(country, title, description, external_url, display_order, dimensions) AS (
  VALUES
  ('Singapura', 'Centro de Confiança para Dados de Sensores', 'O Governo de Singapura desenvolveu o Centro de Confiança para Dados de Sensores como plataforma central de partilha segura de dados entre organismos públicos. A iniciativa disponibiliza serviços integrados de gestão e reutilização de dados ao longo de todo o seu ciclo de vida, contribuindo para uma maior interoperabilidade e confiança na utilização da informação.', 'https://oecd-opsi.org/innovations/trusted-centre-for-sensor-data/', 34, ARRAY['Segurança da Informação e Dados Abertos']),
  ('Irlanda', 'Reforçar a Resiliência da Cibersegurança dos Sistemas e Serviços Públicos', 'O Centro Nacional de Cibersegurança da Irlanda desenvolveu uma norma comum de cibersegurança para todo o setor público e criou uma rede de coordenação entre organismos públicos. A iniciativa promove a partilha de boas práticas e o reforço da capacidade de resposta a incidentes, contribuindo para serviços digitais mais seguros e resilientes.', 'https://oecd-opsi.org/innovations/cyber-security-resilience/', 35, ARRAY['Segurança da Informação e Dados Abertos']),
  ('Canadá', 'Portal Aberto por Defeito', 'O Governo do Canadá desenvolveu um portal de transparência que disponibiliza documentos de trabalho e informação governamental de forma proativa. A iniciativa promove uma cultura de abertura e permite aos cidadãos acompanhar mais de perto os processos de tomada de decisão pública.', 'https://oecd-opsi.org/innovations/open-by-default-portal/', 36, ARRAY['Segurança da Informação e Dados Abertos']),
  ('Peru', 'Reconhecimento Internacional de Dados Abertos', 'O Governo do Peru desenvolveu uma iniciativa de reconhecimento e premiação para incentivar a publicação e utilização de dados abertos. A iniciativa promove a qualidade dos dados, reforça a transparência e estimula a participação cidadã através da reutilização de informação pública', 'https://oecd-opsi.org/innovations/reconocimiento-internacional-en-datos-abiertos-international-award-in-open-data/', 37, ARRAY['Segurança da Informação e Dados Abertos']),
  ('Républica Checa', 'Catálogo Nacional de Dados Abertos', 'O Ministério do Interior da República Checa desenvolveu o Catálogo Nacional de Dados Abertos para assegurar a publicação de conjuntos de dados de acordo com normas europeias de metadados. A iniciativa promove a normalização, a qualidade da informação e a interoperabilidade dos dados abertos entre diferentes níveis da administração pública', 'https://oecd-opsi.org/innovations/national-open-data-catalog-of-the-czech-republic-nodc/', 38, ARRAY['Segurança da Informação e Dados Abertos']),
  ('Bósnia e Herzegovina', 'Iniciativa de Transparência Proativa', 'O Governo da Bósnia e Herzegovina desenvolveu uma iniciativa de transparência proativa que define um conjunto padronizado de informações a divulgar pelas entidades públicas. A iniciativa promove a abertura da administração pública e reforça a consistência e a qualidade da informação disponibilizada aos cidadãos.', 'https://oecd-opsi.org/innovations/proactive-transparency-initiative-in-bosnia-and-herzegovina/', 39, ARRAY['Segurança da Informação e Dados Abertos']),
  ('Peru', 'Observatório Nacional de Prospectiva', 'O Governo do Peru desenvolveu uma plataforma digital que disponibiliza informação estratégica sobre tendências, riscos, oportunidades e cenários futuros. A iniciativa permite a consulta e contribuição por parte de decisores públicos e cidadãos, contribuindo para uma tomada de decisão mais informada e participativa', 'https://oecd-opsi.org/innovations/national-foresight-observatory/', 40, ARRAY['Envolvimento dos Utilizadores']),
  ('Espanha', 'Idea'' Zaragoza', 'A Câmara Municipal de Saragoça desenvolveu a plataforma Idea Zaragoza para reforçar a participação dos cidadãos na definição de políticas e serviços públicos. A iniciativa disponibiliza consultas, inquéritos e mecanismos de recolha de ideias, contribuindo para uma abordagem mais colaborativa e centrada nas necessidades das pessoas.', 'https://oecd-opsi.org/innovations/idea-zaragoza/', 41, ARRAY['Envolvimento dos Utilizadores']),
  ('Estados Unidos da América', 'Desenho Participativo Radical na Administração Pública', 'Organizações públicas nos Estados Unidos implementaram abordagens de desenho participativo que colocam os cidadãos no centro da criação dos serviços públicos. A iniciativa permite que as comunidades participem ao longo de todo o processo de conceção, contribuindo para serviços mais adequados às suas necessidades e experiências.', 'https://oecd-opsi.org/innovations/radical-participatory-design-in-government/', 42, ARRAY['Envolvimento dos Utilizadores']),
  ('Coreia do Sul', 'Rendimento para Ações Climáticas', 'A província de Gyeonggi desenvolveu um modelo que transforma ações ambientais dos cidadãos em valor público mensurável. A iniciativa recompensa comportamentos sustentáveis através de incentivos económicos e promove o envolvimento ativo dos cidadãos na concretização dos objetivos climáticos.', 'https://oecd-opsi.org/innovations/climate-action-opportunity-income/', 43, ARRAY['Envolvimento dos Utilizadores']),
  ('Japão', 'Plataforma de Cocriação para a Transformação Digital', 'A Agência Digital do Japão desenvolveu uma plataforma que promove a partilha de conhecimento e a aprendizagem entre administrações nacionais e locais. A iniciativa facilita a cocriação de políticas e serviços através da colaboração aberta entre funcionários públicos, contribuindo para uma maior coordenação e inovação', 'https://oecd-opsi.org/innovations/digital-transformation-co-creation-platform/', 44, ARRAY['Envolvimento dos Utilizadores']),
  ('Bélgica', 'Desbloquear o Potencial da Inteligência Artificial para Apoiar a Participação Cidadã', 'A CitizenLab desenvolveu ferramentas de inteligência artificial para apoiar a análise de contributos recolhidos em processos de participação pública. A iniciativa permite classificar ideias, identificar tendências emergentes e agrupar contributos semelhantes, contribuindo para uma utilização mais eficaz do feedback dos cidadãos na tomada de decisão pública.', 'https://oecd-opsi.org/innovations/unlocking-the-potential-of-crowdsourcing-for-public-decision-making-with-artificial-intelligence/', 45, ARRAY['Envolvimento dos Utilizadores']),
  ('Brasil', 'Observatório de Prevenção da Violência', 'O município de Caruaru desenvolveu o Observatório de Prevenção da Violência para integrar informação proveniente de diferentes serviços públicos. A iniciativa permite identificar grupos vulneráveis e compreender melhor as causas da violência, contribuindo para intervenções mais preventivas e coordenadas.', 'https://oecd-opsi.org/innovations/violence-prevention-observatory-opv-in-portuguese/', 46, ARRAY['Interoperabilidade']),
  ('Singapura', 'Plataforma Digital Aberta', 'O Governo de Singapura desenvolveu a Open Digital Platform como infraestrutura digital comum para apoiar a iniciativa Smart Nation. A plataforma permite a integração e interoperabilidade entre diferentes sistemas e serviços, contribuindo para uma gestão mais eficiente e coordenada das infraestruturas urbanas.', 'https://oecd-opsi.org/innovations/open-digital-platform-odp/', 47, ARRAY['Interoperabilidade']),
  ('Nova Zelândia', 'SmartStart', 'O SmartStart foi o primeiro serviço entre organismos públicos relativo a um acontecimento de vida disponibilizado online na Nova Zelândia. Facilita o acesso dos neozelandeses a informação e serviços relacionados com o nascimento de um filho, permitindo-lhes: 1) informar-se sobre ter um filho; 2) navegar pelos serviços do governo; 3) aceder e interagir com os serviços; e 4) consentir a reutilização de informação fornecida a um organismo por outro organismo.', 'https://oecd-opsi.org/innovations/smartstart/', 48, ARRAY['Interoperabilidade']),
  ('Camboja', 'CamDX – Plataforma de Interoperabilidade de Dados', 'O Governo do Camboja desenvolveu a plataforma CamDX para permitir a troca segura de dados entre sistemas de informação de diferentes organismos públicos. A iniciativa reduz a duplicação de informação e facilita a integração de serviços digitais, contribuindo para uma administração pública mais interoperável e eficiente', 'https://oecd-opsi.org/innovations/camdx-2/', 49, ARRAY['Interoperabilidade']),
  ('Estónia/Finlândia', 'X-Road Trust Federation para Troca Transfronteiriça de Dados', 'Os governos da Estónia e da Finlândia desenvolveram uma infraestrutura conjunta de interoperabilidade baseada na tecnologia X-Road para permitir a partilha segura de dados entre administrações públicas. A iniciativa facilita o intercâmbio transfronteiriço de informação sobre cidadãos e empresas, contribuindo para serviços mais integrados e eficientes.', 'https://oecd-opsi.org/innovations/x-road-trust-federation-for-cross-border-data-exchange/', 50, ARRAY['Interoperabilidade']),
  ('Polónia', 'Centro Virtual Centralizado de Apoio aos Empresários', 'O Governo da Polónia desenvolveu um centro virtual de apoio aos empresários com uma abordagem multicanal e omnicanal. A iniciativa integra chatbot, chat em direto, videochamada, telefone, linguagem gestual e serviços proativos, contribuindo para uma experiência consistente independentemente do canal utilizado.', 'https://oecd-opsi.org/innovations/9522/', 51, ARRAY['Interoperabilidade']),
  ('Indónesia', 'JAKI – Ecossistema Digital Integrado de Jacarta', 'O Governo de Jacarta desenvolveu a plataforma JAKI para integrar serviços públicos, dados e canais de interação num único ecossistema digital. A iniciativa disponibiliza um ponto único de acesso a múltiplos serviços e promove a coordenação entre organismos públicos, contribuindo para uma experiência mais integrada para os cidadãos', 'https://oecd-opsi.org/innovations/not-just-an-app-but-an-ecosystem-jaki-as-a-digital-public-space-in-jakarta/', 52, ARRAY['Interoperabilidade']),
  ('Coreia do Sul', 'Serviço Integrado baseado em Nuvem para Instituições Públicas', 'A cidade de Suwon desenvolveu um serviço integrado baseado em computação em nuvem para ligar diferentes instituições públicas através de uma infraestrutura comum. A iniciativa permite a partilha de informação e a execução integrada de processos, contribuindo para uma maior eficiência e interoperabilidade organizacional.', 'https://oecd-opsi.org/innovations/private-cloud-based-integrated-business-service-for-public-institutions/', 53, ARRAY['Interoperabilidade'])
), inserted AS (
  INSERT INTO case_studies (country, title, description, external_url, display_order)
  SELECT country, title, description, external_url, display_order FROM raw
  RETURNING id, title
)
INSERT INTO case_study_thematic_priorities (case_study_id, thematic_priority_id)
SELECT i.id, tp.id
FROM raw r
JOIN inserted i ON i.title = r.title
JOIN LATERAL unnest(r.dimensions) AS d(name) ON true
JOIN thematic_priorities tp ON tp.name_pt = d.name;
